### ISSUE TITLE
TDS authorization misconfigured

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esgf-installer#276]
After installing the latest 2.5.14 release, and fixing the ORP problem, data download from the TDS would not work: the TDS kept asking for username/password through the basic authentication pop-up dialog.

**Comment by LucaCinquini** [comment]
The problem can be solved by editing the TDS application configuration file:

/usr/local/tomcat/webapps/thredds/WEB-INF/applicationContext.xml

commenting out this section:



and uncommenting this section:


    <bean id="restrictedDatasetAuthorizer" class="esg.orp.app.tds.TDSAuthorizer" />

**Comment by gardoll** [comment]
Hi Luca, Sorry but which 'commenting out this section' ?

**Comment by LucaCinquini** [comment]
Hi Sebastien, see the comment above again - it turns out the wiki does not display XML sections that are commented out...

**Comment by sashakames** [comment]
This is strange - the applicationContext.xml on the mirror has the second one  uncommented, but not the first, which you said was uncommented.  Did somehow it fail to fetch during your installation @LucaCinquini ?

**Comment by pchengi** [comment]
The distribution servers still have the old version, and TDS has been running fine with it, without the problem being described. The web.xml and applicationContext.xml files persist through updates, if the webapps directory isn't cleared away, and this is likely caused by some old configuration files polluting the space.
