### ISSUE TITLE
Convert test_tds() to Python

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#402]
The test_tds() function should be converted to Python. It should live in the test_thredds.py module.

**Comment by William-Hill** [comment]
Has this test been deprecated as well @sashakames

**Comment by sashakames** [comment]
Probably is.  There should be a test for a successful thredds deployment.  However the existing test code hasn't been updated since the 1.x releases.  

--test does the following:

               --verify | --test)
                    debug_print "VERIFY SERVICES"
                    (( (sel & TEST_BIT) == 0 )) && ((sel+=TEST_BIT))
                    debug_print "sel = $sel "
                    test_postgress
                    test_cdat
                    test_esgcet
                    test_tomcat
                    test_tds
                    exit 0;

But this is not an exhaustive list so other modules don't get tested.  and we can' speak for the reliability of those test themselves.   Bigger question is what testing should be done in the installer and what is better suited for the external test suite (which is a bit heavyweight as I see it).

**Comment by William-Hill** [comment]
I'll close this particular issue.  I'll open another when we decide on a testing plan for a thredds deployment.
