### ISSUE TITLE
Update Java to jdk8-u181

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#619]
Email from Prashanth:

There were a string of CVEs against java 1.8.0_162, so the latest 
available java, 1.8.0_181 has now been made available on coffee, for 
manual upgrades.

**Comment by nathanlcarlson** [comment]
Not sure if we want to do this, but this is the latest release yum has.
```
yum search java-1.8.0-openjdk --showduplicates
...
java-1.8.0-openjdk-1.8.0.181-3.b13.el6_10.x86_64 : OpenJDK Runtime Environment
...
```

**Comment by William-Hill** [comment]
@nathanlcarlson I think eventually installing Java from yum or whatever package manager will be the move. I'm all for moving away from the distribution mirrors as much as possible.  But for now, let's stick with getting Java from the mirror

**Comment by nathanlcarlson** [comment]
Okay, I was just pointing out that `yum` has this same version that we will now be installing from the mirror.

**Comment by pchengi** [comment]
That's openjdk, not Oracle jdk that we use on esgf. There are differences
in bundled libraries and trust packages. I know for a fact that older
esg-search modules and the wget scripts absolutely needed the Oracle jdk,
but a few things have changed since then, but it is still a change that can
break things.

Den mån 8 okt. 2018 23:12nathanlcarlson <notifications@github.com> skrev:
